#!/usr/bin/env bash

if [[ -z $DOTFILES_PATH ]]; then
	echo "Environment variable (DOTFILES_PATH) is not set" >&2
	exit 1
fi

. "$DOTFILES_PATH/lib/log.sh" || exit $?
. "$DOTFILES_PATH/lib/utils.sh" || exit $?

function link_dotfiles() {
	echo "Setting up dotfiles"

	if isfedora; then
		POWERLINE_BASH_CONFIG="/usr/share/powerline/bash/powerline.sh"
		POWERLINE_TMUX_CONFIG="/usr/share/tmux/powerline.conf"
	elif isubuntu; then
		POWERLINE_BASH_CONFIG="/usr/share/powerline/bindings/bash/powerline.sh"
		POWERLINE_TMUX_CONFIG="/usr/share/powerline/bindings/tmux/powerline.conf"
	fi

	printf '%s\n\n%s\n%s\n%s\n' \
		'# Code generated by dotfiles.' \
		"export DOTFILES_PATH='$DOTFILES_PATH'" \
		"export POWERLINE_BASH_CONFIG='$POWERLINE_BASH_CONFIG'" \
		"export POWERLINE_TMUX_CONFIG='$POWERLINE_TMUX_CONFIG'" >~/.exportrc_private

	local dotfiles=(.aliasrc .bash_profile .bashrc .exportrc .imwheelrc .inputrc .tmux.conf)

	for dotfile in "${dotfiles[@]}"; do
		ln -fs "$DOTFILES_PATH/${dotfile}" "$HOME"
	done
}

function link_autostart_apps() {
	[[ $(uname | tolower) != linux ]] && return 0

	echo "Setting up autostart applications"

	local autostart_dir=~/.config/autostart/

	mkdir -p "$autostart_dir"
	ln -fs "$DOTFILES_PATH"/config/autostart/* "$autostart_dir"
}

function link_htop_config() {
	echo "Setting up htop configuration"

	local htop_config_dir="$HOME/.config/htop/"

	mkdir -p "$htop_config_dir"
	ln -fs "$DOTFILES_PATH/htoprc" "$htop_config_dir"
}

function link_sublime_text_config() {
	echo "Setting up Sublime Text configuration"

	case $(uname | tolower) in
	linux)
		local subl_config_dir="$HOME/.config/sublime-text-3/Packages/User/"
		;;
	darwin)
		local subl_config_dir="$HOME/Library/Application Support/Sublime Text 3/Packages/User/"
		;;
	*)
		log_error "Unknown location of Sublime Text's configuration"
		return 1
		;;
	esac

	mkdir -p "$subl_config_dir"
	ln -fs "$DOTFILES_PATH/config/sublime-text-3/Default (Linux).sublime-keymap" "$subl_config_dir"
	ln -fs "$DOTFILES_PATH/config/sublime-text-3/Preferences.sublime-settings" "$subl_config_dir"
	ln -fs "$DOTFILES_PATH/config/sublime-text-3/Package Control.sublime-settings" "$subl_config_dir"
}

function link_powerline_config() {
	echo "Setting up powerline configuration"

	local powerline_config_dir="$HOME/.config/powerline/"

	mkdir -p "$powerline_config_dir"
	ln -fs "$DOTFILES_PATH"/config/powerline/* "$powerline_config_dir"
}

function main() {
	link_dotfiles
	link_autostart_apps
	link_htop_config
	link_powerline_config
	link_sublime_text_config
}

main "$@"
